class ActionExercise {
  String? id;
  String? name;
  String? action_gif;
  String? sets;
  String? ordinalNumber;
  int actingTime;
  String? message;
  bool isRest;
  bool isLastPage;

  ActionExercise({
    required this.id,
    required this.name,
    required this.action_gif,
    required this.actingTime,
    this.sets,
    required this.ordinalNumber,
    this.isRest = false,
    this.message,
    this.isLastPage = false,
  });

  static List<ActionExercise> actionExerciseList() {
    return [
      ActionExercise(
          id: '01',
          name: '① Dead Bug',
          action_gif: 'lib/app/images/actionGif/dead_bug1.gif',
          actingTime: 15,
          sets: '1/2',
          ordinalNumber: '1'),
      ActionExercise(
          id: '02',
          name: '휴식 시간',
          action_gif: 'lib/app/images/actionGif/lying_rest1.gif',
          actingTime: 15,
          ordinalNumber: '1',
          isRest: true,
          message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요'),
      ActionExercise(
          id: '03',
          name: '① Dead bug',
          action_gif: 'lib/app/images/actionGif/dead_bug1.gif',
          actingTime: 15,
          sets: '2/2',
          ordinalNumber: '1'),
      ActionExercise(
          id: '04',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/trunk_surl_sit_up2.gif',
          actingTime: 15,
          ordinalNumber: '1',
          isRest: true,
          message: '다음 동작은 Trunk Curl Sit Up입니다.'),
      ActionExercise(
        id: '05',
        name: '② Trunk Curl Sit Up',
        action_gif: 'lib/app/images/actionGif/trunk_surl_sit_up2.gif',
        actingTime: 30,
        sets: '1/2',
        ordinalNumber: '2',
      ),
      ActionExercise(
        id: '06',
        name: '휴식 시간',
        action_gif: 'lib/app/images/actionGif/trunk_surl_sit_up2_rest.gif',
        actingTime: 15,
        ordinalNumber: '2',
        isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',
      ),
      ActionExercise(
        id: '07',
        name: '② Trunk Curl Sit Up',
        action_gif: 'lib/app/images/actionGif/trunk_surl_sit_up2.gif',
        actingTime: 30,
        sets: '2/2',
        ordinalNumber: '2',
      ),
      ActionExercise(
          id: '08',
          name: '휴식 및 다음동작',
          action_gif: 'lib/app/images/actionGif/superman3.gif',
          actingTime: 15,
          ordinalNumber: '2',
          isRest: true,
          message: '다음 동작은 Superman입니다.'),
      ActionExercise(
        id: '09',
        name: '③ Superman',
        action_gif: 'lib/app/images/actionGif/superman3.gif',
        actingTime: 15,
        sets: '1/3',
        ordinalNumber: '3',
      ),
      ActionExercise(
        id: '10',
        name: '휴식 시간',
        action_gif: 'lib/app/images/actionGif/superman3_rest.gif',
        actingTime: 30,
        ordinalNumber: '3',
        isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',
      ),
      ActionExercise(
        id: '11',
        name: '③ Superman',
        action_gif: 'lib/app/images/actionGif/superman3.gif',
        actingTime: 15,
        sets: '2/3',
        ordinalNumber: '3',
      ),
      ActionExercise(
        id: '12',
        name: '휴식 시간',
        action_gif: 'lib/app/images/actionGif/superman3_rest.gif',
        actingTime: 30,
        ordinalNumber: '3',
        isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',
      ),
      ActionExercise(
        id: '13',
        name: '③ Superman',
        action_gif: 'lib/app/images/actionGif/superman3.gif',
        actingTime: 15,
        sets: '3/3',
        ordinalNumber: '3',
      ),
      ActionExercise(
          id: '14',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/stretching_illiopsoas4_1.gif',
          actingTime: 30,
          ordinalNumber: '3',
          isRest: true,
          message: '다음 동작은 장요근 늘리기입니다.'),
      ActionExercise(
        id: '15',
        name: '④ 장요근 늘리기',
        action_gif: 'lib/app/images/actionGif/stretching_illiopsoas4_1.gif',
        actingTime: 25,
        sets: '1/2',
        ordinalNumber: '4',
      ),
      ActionExercise(
        id: '16',
        name: '휴식 시간',
        action_gif: 'lib/app/images/actionGif/stretching_illiopsoas4_rest.gif',
        actingTime: 10,
        ordinalNumber: '4',
        isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',
      ),
      ActionExercise(
        id: '17',
        name: '④ 장요근 늘리기',
        action_gif: 'lib/app/images/actionGif/stretching_illiopsoas4_2.gif',
        actingTime: 25,
        sets: '2/2',
        ordinalNumber: '4',
      ),
      ActionExercise(
          id: '18',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/bird_dog5.gif',
          actingTime: 10,
          ordinalNumber: '4',
          isRest: true,
          message: '다음 동작은 Bird Dog입니다.'),
      ActionExercise(
        id: '19',
        name: '⑤ Bird Dog',
        action_gif: 'lib/app/images/actionGif/bird_dog5.gif',
        actingTime: 80,
        sets: '1/1',
        ordinalNumber: '5',
      ),
      ActionExercise(
          id: '20',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/bridge6.gif',
          actingTime: 30,
          ordinalNumber: '5',
          isRest: true,
          message: '다음 동작은 Bridge입니다.'),
      ActionExercise(
        id: '21',
        name: '⑥ Bridge',
        action_gif: 'lib/app/images/actionGif/bridge6.gif',
        actingTime: 10,
        sets: '1/2',
        ordinalNumber: '6',
      ),
      ActionExercise(
          id: '22',
          name: '휴식 시간',
          action_gif: 'lib/app/images/actionGif/bridge6_rest.gif',
          actingTime: 10,
          ordinalNumber: '6',
          isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',),
      ActionExercise(
        id: '23',
        name: '⑥ Bridge',
        action_gif: 'lib/app/images/actionGif/bridge6.gif',
        actingTime: 10,
        sets: '2/2',
        ordinalNumber: '6',
      ),
      ActionExercise(
          id: '24',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/cobra7.gif',
          actingTime: 10,
          ordinalNumber: '6',
          isRest: true,
          message: '다음 동작은 코브라 자세입니다.'),
      ActionExercise(
        id: '25',
        name: '⑦ 코브라 자세',
        action_gif: 'lib/app/images/actionGif/cobra7.gif',
        actingTime: 15,
        sets: '1/3',
        ordinalNumber: '7',
      ),
      ActionExercise(
          id: '26',
          name: '휴식 시간',
          action_gif: 'lib/app/images/actionGif/cobra7_rest.gif',
          actingTime: 5,
          ordinalNumber: '7',
          isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',),
      ActionExercise(
        id: '27',
        name: '⑦ 코브라 자세',
        action_gif: 'lib/app/images/actionGif/cobra7.gif',
        actingTime: 15,
        sets: '2/3',
        ordinalNumber: '7',
      ),
      ActionExercise(
          id: '28',
          name: '휴식 시간',
          action_gif: 'lib/app/images/actionGif/cobra7_rest.gif',
          actingTime: 5,
          ordinalNumber: '7',
          isRest: true,
        message: '운동 중 너무 힘드시거나 어지러우시면 즉시 운동을 종료해주세요',),
      ActionExercise(
        id: '29',
        name: '⑦ 코브라 자세',
        action_gif: 'lib/app/images/actionGif/cobra7.gif',
        actingTime: 15,
        sets: '3/3',
        ordinalNumber: '7',
      ),
      ActionExercise(
          id: '30',
          name: '휴식 및 다음 동작',
          action_gif: 'lib/app/images/actionGif/stretching8.gif',
          actingTime: 5,
          ordinalNumber: '7',
          isRest: true,
          message: '다음 동작은 누워서 무릎 갖다 대기입니다.'),
      ActionExercise(
        id: '31',
        name: '⑧ 누워서 무릎 갖다 대기',
        action_gif: 'lib/app/images/actionGif/stretching8.gif',
        actingTime: 15,
        sets: '1/2',
        ordinalNumber: '8',
      ),
      ActionExercise(
        id: '32',
        name: '⑧ 누워서 무릎 갖다 대기',
        action_gif: 'lib/app/images/actionGif/stretching8.gif',
        actingTime: 15,
        sets: '2/2',
        ordinalNumber: '8',
      ),
      ActionExercise(
        id: '33',
        name: '운동이 종료되었습니다!',
        action_gif: 'lib/app/images/muscleImages/fire_cracker.png',
        actingTime: 20,
        ordinalNumber: 'End',
        sets: '',
        isLastPage: true,
      )
    ];
  }
}
